"""
SuperCollider NRT Code Generator.

Converts a list of SoundEvent objects into a SuperCollider .scd script
that uses Score.recordNRT to render audio offline.

SC NRT rendering pipeline:
  1. Load all Sonic Pi synthdefs from the compiled/ directory
  2. Allocate buffers for each unique sample file
  3. Schedule /s_new events for synths (with add-to-head for sources)
  4. Schedule /n_free events after each synth's ADSR duration
  5. Schedule /s_new for FX (add-to-tail so they read after sources write)
  6. Schedule /n_free for FX at their close time
  7. Call Score.recordNRT to render to WAV
"""
from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from .evaluator import SoundEvent


# ---------------------------------------------------------------------------
# Codegen
# ---------------------------------------------------------------------------

class SCNRTCodegen:
    """
    Args:
        events:          Sorted list of SoundEvent objects.
        output_wav:      Absolute path for the rendered WAV file.
        synthdef_dir:    Path to sonic-pi/etc/synthdefs/compiled/
        sample_rate:     Output sample rate (Hz).
        channels:        Number of output channels (2 = stereo).
        tail_time:       Extra seconds appended after the last event.
        score_osc_path:  Temp path for the OSC score file sclang writes.
    """

    def __init__(
        self,
        events: list[SoundEvent],
        output_wav: str,
        synthdef_dir: str,
        sample_rate: int = 44100,
        channels: int = 2,
        tail_time: float = 2.0,
        score_osc_path: str = "/tmp/nrt_score.osc",
    ):
        self.events = sorted(events, key=lambda e: e.time)
        self.output_wav = output_wav
        self.synthdef_dir = synthdef_dir
        self.sample_rate = sample_rate
        self.channels = channels
        self.tail_time = tail_time
        self.score_osc_path = score_osc_path

        # Collect unique sample paths → buffer IDs
        self._sample_buffers: dict[str, int] = {}
        self._next_buf_id = 0
        self._collect_buffers()

        self._duration = self._compute_duration()

    # ── Buffer management ────────────────────────────────────────────────

    def _collect_buffers(self):
        for evt in self.events:
            if evt.kind == 'sample':
                path = evt.synth_name  # stored as path
                if path not in self._sample_buffers:
                    self._sample_buffers[path] = self._next_buf_id
                    self._next_buf_id += 1

    def _buf_id(self, path: str) -> int:
        return self._sample_buffers.get(path, 0)

    # ── Duration ────────────────────────────────────────────────────────

    def _compute_duration(self) -> float:
        if not self.events:
            return self.tail_time
        latest = max(e.time + e.duration() for e in self.events)
        return latest + self.tail_time

    # ── Main generation ──────────────────────────────────────────────────

    def generate(self) -> str:
        lines: list[str] = []
        lines.append(self._header())
        lines.append(self._load_synthdefs())
        lines.append(self._buffer_allocs())
        lines.append(self._synth_events())
        lines.append(self._footer())
        return "\n".join(filter(None, lines))

    # ── Header ──────────────────────────────────────────────────────────

    def _header(self) -> str:
        return (
            "// Generated by sonic-pi-transpiler\n"
            "// https://github.com/sonic-pi-net/sonic-pi\n"
            "(\n"
            "var score;\n"
            "score = [];\n"
        )

    # ── Load synthdefs ───────────────────────────────────────────────────

    def _load_synthdefs(self) -> str:
        # Escape backslashes for SC string literals
        path = self.synthdef_dir.replace('\\', '/')
        return f'score = score.add([0.0, ["/d_loadDir", "{path}"]]);\n'

    # ── Buffer allocations ───────────────────────────────────────────────

    def _buffer_allocs(self) -> str:
        if not self._sample_buffers:
            return ''
        lines = ['// Buffer allocations for samples']
        for path, buf_id in self._sample_buffers.items():
            esc_path = path.replace('\\', '/')
            lines.append(
                f'score = score.add([0.001, ["/b_allocRead", {buf_id}, "{esc_path}", 0, 0]]);'
            )
        return '\n'.join(lines) + '\n'

    # ── Synth / sample / FX events ───────────────────────────────────────

    def _synth_events(self) -> str:
        lines = ['// Sound events']

        for evt in self.events:
            if evt.kind == 'synth':
                lines.extend(self._render_synth(evt))
            elif evt.kind == 'sample':
                lines.extend(self._render_sample(evt))
            elif evt.kind == 'fx_open':
                lines.extend(self._render_fx_open(evt))
            elif evt.kind == 'fx_close':
                lines.extend(self._render_fx_close(evt))

        return '\n'.join(lines) + '\n'

    def _render_synth(self, evt: SoundEvent) -> list[str]:
        t = evt.time
        dur = evt.duration()
        nid = evt.node_id

        args = dict(evt.args)
        args.pop('out_bus', None)
        args['out_bus'] = evt.bus_out

        # addAction 0 = addToHead (sources before FX in signal chain)
        msg = self._s_new_msg(evt.synth_name, nid, 0, 0, args)
        s = f'score = score.add([{t:.6f}, {msg}]);'

        free_t = t + dur
        f = f'score = score.add([{free_t:.6f}, ["/n_free", {nid}]]);'
        return [s, f]

    def _render_sample(self, evt: SoundEvent) -> list[str]:
        t = evt.time
        path = evt.synth_name  # file path or symbolic name

        buf_id = self._buf_id(path)

        # Determine mono vs stereo (heuristic: can't know without loading)
        # Use stereo player by default (works for mono too in SC)
        player = 'sonic-pi-basic_stereo_player'

        args: dict[str, Any] = {
            'buf':     buf_id,
            'amp':     evt.args.get('amp',     1.0),
            'pan':     evt.args.get('pan',     0.0),
            'rate':    evt.args.get('rate',    1.0),
            'start':   evt.args.get('start',   0.0),
            'finish':  evt.args.get('finish',  1.0),
            'attack':  evt.args.get('attack',  0.0),
            'sustain': evt.args.get('sustain', -1.0),  # -1 = auto-stretch
            'release': evt.args.get('release', 0.0),
            'out_bus': evt.bus_out,
        }

        # beat_stretch: caller stores it; we can't resolve without sample duration
        # Pass it through as rate=1 (user must ensure BPM-aware rate externally)

        nid = evt.node_id
        msg = self._s_new_msg(player, nid, 0, 0, args)
        s = f'score = score.add([{t:.6f}, {msg}]);'

        # Sample player self-terminates via doneAction:2 in the synthdef
        return [s]

    def _render_fx_open(self, evt: SoundEvent) -> list[str]:
        t = evt.time
        nid = evt.node_id
        args = dict(evt.args)

        # addAction 1 = addToTail (FX reads buses that sources have written)
        msg = self._s_new_msg(evt.synth_name, nid, 1, 0, args)
        return [f'score = score.add([{t:.6f}, {msg}]);']

    def _render_fx_close(self, evt: SoundEvent) -> list[str]:
        t = evt.time
        nid = evt.node_id
        return [f'score = score.add([{t:.6f}, ["/n_free", {nid}]]);']

    # ── Footer ───────────────────────────────────────────────────────────

    def _footer(self) -> str:
        dur = self._duration
        osc_path = self.score_osc_path.replace('\\', '/')
        wav_path = self.output_wav.replace('\\', '/')
        header_fmt = "WAV"
        sample_fmt = "int24"

        return (
            f"// End marker\n"
            f"score = score.add([{dur:.4f}, [\"/c_set\", 0, 0]]);\n\n"
            f"// Render\n"
            f"Score.recordNRT(\n"
            f"    score,\n"
            f"    \"{osc_path}\",\n"
            f"    outputFilePath: \"{wav_path}\",\n"
            f"    headerFormat: \"{header_fmt}\",\n"
            f"    sampleFormat: \"{sample_fmt}\",\n"
            f"    sampleRate: {self.sample_rate},\n"
            f"    duration: {dur:.4f},\n"
            f"    options: ServerOptions.new.numOutputBusChannels_({self.channels}),\n"
            f"    action: {{ \"NRT render complete: {wav_path}\".postln; 0.exit }}\n"
            f");\n"
            f")\n"
        )

    # ── Helpers ──────────────────────────────────────────────────────────

    def _s_new_msg(
        self,
        synth_name: str,
        node_id: int,
        add_action: int,
        target_id: int,
        args: dict,
    ) -> str:
        """
        Build a SC /s_new OSC message as a SuperCollider Array literal.
        Format: ["/s_new", "name", nodeID, addAction, targetID, key, val, ...]
        """
        parts: list[str] = [
            '"/s_new"',
            f'"{synth_name}"',
            str(node_id),
            str(add_action),
            str(target_id),
        ]
        for k, v in args.items():
            parts.append(f'"{k}"')
            parts.append(self._sc_val(v))
        return '[' + ', '.join(parts) + ']'

    @staticmethod
    def _sc_val(v: Any) -> str:
        """Format a Python value as a SuperCollider literal."""
        if isinstance(v, bool):
            return '1' if v else '0'
        if isinstance(v, int):
            return str(v)
        if isinstance(v, float):
            # 6 decimal places; avoids SC float parsing issues
            return f'{v:.6f}'
        if isinstance(v, str):
            return f'"{v}"'
        if v is None:
            return '0'
        return str(v)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate(
    events: list[SoundEvent],
    output_wav: str,
    synthdef_dir: str,
    sample_rate: int = 44100,
    channels: int = 2,
    tail_time: float = 2.0,
) -> str:
    """Generate a SC NRT .scd script from a list of SoundEvents."""
    cg = SCNRTCodegen(
        events=events,
        output_wav=output_wav,
        synthdef_dir=synthdef_dir,
        sample_rate=sample_rate,
        channels=channels,
        tail_time=tail_time,
    )
    return cg.generate()
